spring:
  application:
    name: person-service
  output:
    ansi:
      enabled: always

management:
  endpoint:
    service-registry:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.example: debug

