spring:
  application:
    name: person-service
  output:
    ansi:
      enabled: always
  cloud:
    kubernetes:
      discovery:
        include-not-ready-addresses: true
        all-namespaces: true

management:
  endpoint:
    service-registry:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.example: debug

